#!/usr/bin/env bash

shopt -s nullglob globstar

pw_files=$(gopass ls --flat)
password=$(printf '%s\n' "${pw_files[@]}" | rofi -font "hack nerd font 12" -theme Arc-Dark -p '🔑 ' -dmenu "$@")

[[ -n $password ]] || exit

gopass show -c $password
